version: '3.8'

services:
  pet-project-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-project-go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    depends_on:
      - postgres
    networks:
      - auth-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: auth-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@auth.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - auth-network
    restart: unless-stopped

networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data: